apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  username: user
  password: pwd
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
   - name: mypod
     image: alpine
     imagePullPolicy: IfNotPresent
     command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
     env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
            optional: false
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
            optional: false
     resources:
        limits:
          cpu: 200m
          memory: 512Mi
     volumeMounts:
     - name: foo
       mountPath: "/etc/foo"
       readOnly: true
    
  volumes:
  - name: foo
    secret:
      secretName: mysecret
      optional: false