#Vagrant.configure("2") do |config|
# 	config.vm.box = "bento/ubuntu-20.04"
#    config.vm.network "forwarded_port", guest: 19999, host: 19999
#    config.vm.provider "virtualbox" do |v|
#        v.memory = 1024
#        v.cpus = 2
#    end
# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = {
  'netology1' => '10',
  'netology2' => '60',
  'netology3' => '90',
  'netology4' => '120'
}

Vagrant.configure("2") do |config|
  config.vm.network "private_network", virtualbox__intnet: true, auto_config: false
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end
  config.vm.box = "bento/ubuntu-20.04"

  boxes.each do |k, v|
    config.vm.define k do |node|
      node.vm.provision "shell" do |s|
        s.inline = "hostname $1;"\
          "ip addr add $2 dev eth1;"\
          "ip link set dev eth1 up;"\
          "apt -y install nginx;"\
          "mkdir -p /data/www;"\
          "echo Hello from $1 >> /data/www/index.html;"
        s.args = [k, "172.28.128.#{v}/24"]
      end
    end
  end

end
