---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stage
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: stage-front-back
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stage
spec:
  ports:
    - name: backend
      port: 9000
  selector:
    app: stage-front-back
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: stage
spec:
  ports:
    - name: pg
      port: 5432
  selector:
    app: postgres
  type: ClusterIP
