#!/usr/bin/env bash

# Get message from commit
msg=$(cat $1)

# Check message struct - [00-string-00-string]:string
if [[ $msg =~ ^\[[0-9]{2}-[a-z]{1,}-[0-9]{2}-[a-z]{1,}\]:. ]]; then
  # Check message lenght
  if [[ ${#msg} -gt 30 ]]; then
    echo "Message more than 30 symbols"
    # return error code 1 != 0
    exit 1
  fi
else
  echo "Message not in format [00-string-00-string]:string"
  # return error code 1 != 0
  exit 1
fi