all:
  hosts:
    cp1:
      ansible_host: 51.250.104.111
      ansible_user: user
    node1:
      ansible_host: 51.250.99.137
      ansible_user: user
    node2:
      ansible_host: 51.250.98.112
      ansible_user: user
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}