---
apiVersion: v1
kind: Service
metadata:
  name: api-ext
  namespace: prod
spec:
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: api-ext
  namespace: prod
subsets:
  - addresses:
      - ip: 18.215.122.215
    ports:
      - name: http
        port: 80
      - name: https
        port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: api-ext-name
  namespace: prod
spec:
  type: ExternalName
  externalName: eu.httpbin.org